CC        = gcc
CFLAGS    = -g -O0
LFLAGS    = 
OBJS      = $(SOURCES:.c=.o)
LSTS      = $(SOURCES:.c=.lst)
PROJECT   = openec.gcc
SOURCES   = main.c   battery.c ds2756.c matrix_3x3.c port_0x6c.c \
            sfr_dump.c sfr_rw.c states.c timer.c uart.c \
            watchdog.c build.c

$(PROJECT): $(OBJS)
	$(CC) $(CFLAGS) -o $(PROJECT) $(OBJS) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $<

clean :
	rm -f $(ASMS) $(LSTS) $(OBJS)
	rm -f $(PROJECT)

